[font]
size = 12.0

[font.bold]
family = "Agave Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "Agave Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "Agave Nerd Font Mono"
style = "Italic"

[font.normal]
family = "Agave Nerd Font Mono"
style = "Regular"
